mysql:
  user: root 
  host: db
  port: 3306
  existingPasswordSecret:
    name: "mysql-secret"
    key: "mysql-root-password"

serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus
